### ISSUE TITLE
npm vulnerabilities

### ISSUE THREAD

**Issue by osban** [CreaturesInUnitards/mithril-timepicker#3]
**Danger!**

According to npm:
```
 Moderate: Denial of Service
 Package: js-yaml
 Patched in: >=3.13.0
 Dependency of: mithril-timepicker
 Path: mithril-timepicker > css-loader > cssnano > postcss-svgo > svgo > js-yaml
 More info: https://npmjs.com/advisories/788

 High: Code Injection
 Package: js-yaml
 Patched in: >=3.13.1
 Dependency of: mithril-timepicker
 Path: mithril-timepicker > css-loader > cssnano > postcss-svgo > svgo > js-yaml
 More info: https://npmjs.com/advisories/813

found 2 vulnerabilities (1 moderate, 1 high) in 924 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```
Is there an easy solution?

**Comment by CreaturesInUnitards** [comment]
@osban just do `npm audit fix --force` if you’re worried about it. The warnings won’t go away, but you’ll notice that the updated version of `js-yaml` is compliant.

**Comment by osban** [comment]
Tbh, I don't know whether I should be worried or not...how problematic are these vulnerabilities?

**Comment by CreaturesInUnitards** [comment]
It’s one thing if these vulnerabilities are in use in production code, but in this case it’s only for the build system, so I’m not concerned at all.

**Comment by CreaturesInUnitards** [comment]
To be clear: the only dependency this component has is Mithril.

**Comment by osban** [comment]
Cool, thanks 😃
